version: '3.8'

services:
  web:
    build: .
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SETTINGS_MODULE=readmailweb.settings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    restart: always 