version: '3.8'

services:
  web:
    build: .
    ports:
      - "8002:8002"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
    restart: always
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 